// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webdoctruyen.Models;

#nullable disable

namespace Webdoctruyen.Migrations
{
    [DbContext(typeof(ApptruyenContext))]
    partial class ApptruyenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webdoctruyen.Models.Danhgium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdTaikhoan")
                        .HasColumnType("int")
                        .HasColumnName("id_taikhoan");

                    b.Property<int>("IdTruyen")
                        .HasColumnType("int")
                        .HasColumnName("id_truyen");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("noidung");

                    b.ToTable("danhgia", (string)null);
                });

            modelBuilder.Entity("Webdoctruyen.Models.Taikhoan", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("matkhau");

                    b.Property<int>("Phanquyen")
                        .HasColumnType("int")
                        .HasColumnName("phanquyen");

                    b.Property<string>("Tentaikhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tentaikhoan");

                    b.ToTable("taikhoan", (string)null);
                });

            modelBuilder.Entity("Webdoctruyen.Models.Truyen", b =>
                {
                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("anh");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdTk")
                        .HasColumnType("int")
                        .HasColumnName("id_tk");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("noidung");

                    b.Property<string>("Tentruyen")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("tentruyen");

                    b.ToTable("truyen", (string)null);
                });

            modelBuilder.Entity("Webdoctruyen.Models.Voice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdTruyen")
                        .HasColumnType("int")
                        .HasColumnName("id_truyen");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("link");

                    b.Property<int>("Nhanvat")
                        .HasColumnType("int")
                        .HasColumnName("nhanvat");

                    b.ToTable("voice", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
